### ISSUE TITLE
Crash when selecting NULL for GEOGRAPHY/GEOMETRY data type

### ISSUE THREAD

**Issue by robverschoor** [microsoft/go-sqlcmd#553]
This sequence crashes in v.1.8.1 (and 1.8.0, other versions not tested). Same for GEOMETRY type.

```
1> declare @v geography
2> select @v
3> go
panic: not implemented makeGoLangScanType for type 240

goroutine 1 [running]:
github.com/microsoft/go-mssqldb.makeGoLangScanType({0xf0, 0x0, 0x21, 0xffff, 0x0, 0x0, {0xc0004d0000, 0xffff, 0xffff}, {
0x0, ...}, ...})
        /go/pkg/mod/github.com/microsoft/go-mssqldb@v1.7.2/types.go:1141 +0xd74
github.com/microsoft/go-mssqldb.(*Rowsq).ColumnTypeScanType(0x1ef3450?, 0x1494100?)
        /go/pkg/mod/github.com/microsoft/go-mssqldb@v1.7.2/mssql.go:1448 +0x185
[...]
```

**Comment by dlevy-msft-sql** [comment]
This was fixed upstream in go-mssqldb. The issue was that makeGoLangScanType in v1.7.2 had no case for typeUdt (0xf0 = 240). The current driver version (v1.9.8) handles it: `case typeUdt: return reflect.TypeOf([]byte{})`. Since go-sqlcmd now uses go-mssqldb v1.9.8, this panic no longer occurs.
